create table customer (
	customer_id INT,
	cust_name VARCHAR(50),
	city VARCHAR(50),
	grade INT,
	salesman_id INT
);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (1, 'Benoite', 'Indonesia', 502, 14);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (2, 'Minnnie', 'China', 854, 15);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (3, 'Sybilla', 'France', 324, 16);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (4, 'Ebonee', 'Indonesia', 192, 17);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (5, 'Nowell', 'Croatia', 618, 18);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (6, 'Chlo', 'Russia', 941, 19);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (7, 'Richart', 'Czech Republic', 913, 20);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (8, 'Felipe', 'Portugal', 878, 21);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (9, 'Susannah', 'Thailand', 287, 22);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (10, 'Germaine', 'Uganda', 641, 23);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (11, 'Fanechka', 'El Salvador', 847, 24);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (12, 'Liane', 'Russia', 128, 25);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (13, 'Lori', 'China', 783, 26);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (14, 'Lazare', 'Indonesia', 884, 27);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (15, 'Dominga', 'South Africa', 290, 28);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (16, 'Parrnell', 'Chile', 194, 29);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (17, 'Tadio', 'China', 610, 30);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (18, 'Vincent', 'Russia', 135, 31);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (19, 'Orelia', 'Russia', 233, 32);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (20, 'Madalyn', 'Malaysia', 474, 33);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (21, 'Felipa', 'Brazil', 848, 34);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (22, 'Dennet', 'Russia', 964, 35);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (23, 'Jo', 'Russia', 947, 36);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (24, 'Harmonie', 'Portugal', 111, 37);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (25, 'Euphemia', 'Nepal', 740, 38);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (26, 'Bancroft', 'Philippines', 450, 39);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (27, 'Rolf', 'Iran', 111, 40);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (28, 'Bourke', 'Paraguay', 949, 41);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (29, 'Antony', 'Djibouti', 249, 42);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (30, 'Opalina', 'Indonesia', 486, 43);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (31, 'Lotty', 'Ukraine', 359, 44);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (32, 'Doug', 'Poland', 404, 45);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (33, 'Portie', 'Russia', 902, 46);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (34, 'Wilt', 'Japan', 247, 47);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (35, 'Carley', 'Mexico', 813, 48);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (36, 'Rolando', 'China', 512, 49);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (37, 'Carmela', 'China', 364, 50);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (38, 'Marieann', 'Luxembourg', 773, 51);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (39, 'Katerina', 'China', 478, 52);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (40, 'Hanni', 'Indonesia', 739, 53);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (41, 'Corliss', 'Japan', 469, 54);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (42, 'Norton', 'Peru', 798, 55);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (43, 'Edik', 'Colombia', 427, 56);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (44, 'Creigh', 'China', 846, 57);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (45, 'Franky', 'Poland', 937, 58);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (46, 'Theodor', 'Poland', 356, 59);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (47, 'Noell', 'China', 451, 60);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (48, 'Genovera', 'Colombia', 714, 61);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (49, 'Riki', 'Bulgaria', 280, 62);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (50, 'Ashien', 'Russia', 142, 63);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (51, 'Eddy', 'Philippines', 858, 64);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (52, 'Rosaleen', 'Poland', 580, 65);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (53, 'Cymbre', 'Indonesia', 640, 66);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (54, 'Ebenezer', 'Peru', 886, 67);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (55, 'Millard', 'Japan', 577, 68);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (56, 'Siana', 'Nigeria', 581, 69);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (57, 'Sholom', 'Russia', 368, 70);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (58, 'Joey', 'Norway', 205, 71);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (59, 'Bree', 'Venezuela', 493, 72);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (60, 'Hugues', 'China', 493, 73);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (61, 'Kyrstin', 'Russia', 876, 74);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (62, 'Gilli', 'China', 1000, 75);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (63, 'Keary', 'China', 624, 76);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (64, 'Melisent', 'Vietnam', 110, 77);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (65, 'Harri', 'Poland', 927, 78);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (66, 'Lou', 'Indonesia', 422, 79);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (67, 'Adrianne', 'China', 897, 80);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (68, 'Helaina', 'Sweden', 335, 81);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (69, 'Florenza', 'Ireland', 362, 82);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (70, 'Anastassia', 'Portugal', 511, 83);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (71, 'Gena', 'Syria', 929, 84);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (72, 'Evvie', 'Brazil', 790, 85);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (73, 'Edan', 'China', 239, 86);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (74, 'Elna', 'Colombia', 807, 87);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (75, 'Camey', 'China', 471, 88);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (76, 'Moyra', 'China', 838, 89);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (77, 'Kellen', 'South Korea', 176, 90);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (78, 'Janice', 'Indonesia', 392, 91);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (79, 'Madella', 'Argentina', 434, 92);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (80, 'Reube', 'Mexico', 533, 93);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (81, 'Honoria', 'Brazil', 390, 94);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (82, 'Charleen', 'Sweden', 336, 95);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (83, 'Fulton', 'Estonia', 394, 96);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (84, 'Erhart', 'China', 916, 97);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (85, 'Jamima', 'China', 575, 98);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (86, 'Keary', 'Argentina', 529, 99);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (87, 'Mord', 'Portugal', 840, 100);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (88, 'Erskine', 'Indonesia', 274, 1);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (89, 'Verena', 'Colombia', 210, 2);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (90, 'Adlai', 'China', 869, 3);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (91, 'Maryrose', 'China', 490, 4);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (92, 'Meyer', 'Russia', 687, 5);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (93, 'Wilburt', 'Yemen', 896, 6);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (94, 'Kirby', 'Russia', 697, 7);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (95, 'Meggy', 'Netherlands', 634, 8);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (96, 'Lucinda', 'Peru', 326, 9);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (97, 'Anna', 'Uganda', 572, 10);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (98, 'Balduin', 'Mexico', 354, 11);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (99, 'Rheta', 'China', 318, 12);
insert into customer (customer_id, cust_name, city, grade, salesman_id) values (100, 'Franny', 'Indonesia', 920, 13);
