create table salesman (
	salesman_id INT,
	name VARCHAR(50),
	city VARCHAR(50),
	commission INT
);
insert into salesman (salesman_id, name, city, commission) values (1, 'Goldi', 'Philippines', 13);
insert into salesman (salesman_id, name, city, commission) values (2, 'Gilbert', 'Indonesia', 9);
insert into salesman (salesman_id, name, city, commission) values (3, 'Antoni', 'Indonesia', 9);
insert into salesman (salesman_id, name, city, commission) values (4, 'Nisse', 'Netherlands', 13);
insert into salesman (salesman_id, name, city, commission) values (5, 'Rikki', 'Ukraine', 14);
insert into salesman (salesman_id, name, city, commission) values (6, 'Batholomew', 'Japan', 11);
insert into salesman (salesman_id, name, city, commission) values (7, 'Donia', 'United States', 9);
insert into salesman (salesman_id, name, city, commission) values (8, 'Gustavo', 'Indonesia', 14);
insert into salesman (salesman_id, name, city, commission) values (9, 'Katlin', 'Indonesia', 14);
insert into salesman (salesman_id, name, city, commission) values (10, 'Harlen', 'Vietnam', 14);
insert into salesman (salesman_id, name, city, commission) values (11, 'Jakob', 'Ukraine', 13);
insert into salesman (salesman_id, name, city, commission) values (12, 'Court', 'United States', 14);
insert into salesman (salesman_id, name, city, commission) values (13, 'Joya', 'Brazil', 9);
insert into salesman (salesman_id, name, city, commission) values (14, 'Rani', 'Greece', 13);
insert into salesman (salesman_id, name, city, commission) values (15, 'Leone', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (16, 'Meagan', 'Canada', 10);
insert into salesman (salesman_id, name, city, commission) values (17, 'Forrest', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (18, 'Gabrielle', 'China', 13);
insert into salesman (salesman_id, name, city, commission) values (19, 'Duff', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (20, 'Juliette', 'Zimbabwe', 9);
insert into salesman (salesman_id, name, city, commission) values (21, 'Corbie', 'Indonesia', 9);
insert into salesman (salesman_id, name, city, commission) values (22, 'Vevay', 'Poland', 14);
insert into salesman (salesman_id, name, city, commission) values (23, 'Tobe', 'China', 10);
insert into salesman (salesman_id, name, city, commission) values (24, 'Beilul', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (25, 'Lucilia', 'Mexico', 9);
insert into salesman (salesman_id, name, city, commission) values (26, 'Analise', 'Indonesia', 9);
insert into salesman (salesman_id, name, city, commission) values (27, 'Terra', 'Guatemala', 13);
insert into salesman (salesman_id, name, city, commission) values (28, 'Brier', 'Indonesia', 13);
insert into salesman (salesman_id, name, city, commission) values (29, 'Stormi', 'Portugal', 12);
insert into salesman (salesman_id, name, city, commission) values (30, 'Marielle', 'France', 14);
insert into salesman (salesman_id, name, city, commission) values (31, 'Nessy', 'Sudan', 14);
insert into salesman (salesman_id, name, city, commission) values (32, 'Blair', 'Greece', 9);
insert into salesman (salesman_id, name, city, commission) values (33, 'Perice', 'China', 14);
insert into salesman (salesman_id, name, city, commission) values (34, 'Lea', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (35, 'Zora', 'Venezuela', 11);
insert into salesman (salesman_id, name, city, commission) values (36, 'Bondie', 'Portugal', 12);
insert into salesman (salesman_id, name, city, commission) values (37, 'Dunn', 'Poland', 9);
insert into salesman (salesman_id, name, city, commission) values (38, 'La verne', 'China', 14);
insert into salesman (salesman_id, name, city, commission) values (39, 'Clementia', 'Poland', 10);
insert into salesman (salesman_id, name, city, commission) values (40, 'Chico', 'Poland', 9);
insert into salesman (salesman_id, name, city, commission) values (41, 'Collen', 'Indonesia', 14);
insert into salesman (salesman_id, name, city, commission) values (42, 'Skippy', 'China', 10);
insert into salesman (salesman_id, name, city, commission) values (43, 'Corie', 'Indonesia', 13);
insert into salesman (salesman_id, name, city, commission) values (44, 'Crissie', 'United States', 14);
insert into salesman (salesman_id, name, city, commission) values (45, 'Crissy', 'China', 11);
insert into salesman (salesman_id, name, city, commission) values (46, 'Jesse', 'Portugal', 9);
insert into salesman (salesman_id, name, city, commission) values (47, 'Erek', 'United Arab Emirates', 13);
insert into salesman (salesman_id, name, city, commission) values (48, 'Jessica', 'Bangladesh', 14);
insert into salesman (salesman_id, name, city, commission) values (49, 'Vassili', 'Jordan', 13);
insert into salesman (salesman_id, name, city, commission) values (50, 'Ileana', 'China', 14);
insert into salesman (salesman_id, name, city, commission) values (51, 'Sheilah', 'Croatia', 13);
insert into salesman (salesman_id, name, city, commission) values (52, 'Hyatt', 'Philippines', 14);
insert into salesman (salesman_id, name, city, commission) values (53, 'Vera', 'Brazil', 11);
insert into salesman (salesman_id, name, city, commission) values (54, 'Read', 'Indonesia', 10);
insert into salesman (salesman_id, name, city, commission) values (55, 'Daveen', 'Canada', 11);
insert into salesman (salesman_id, name, city, commission) values (56, 'Antoine', 'Poland', 12);
insert into salesman (salesman_id, name, city, commission) values (57, 'Teodor', 'South Korea', 9);
insert into salesman (salesman_id, name, city, commission) values (58, 'Kerwinn', 'China', 13);
insert into salesman (salesman_id, name, city, commission) values (59, 'Christel', 'Croatia', 13);
insert into salesman (salesman_id, name, city, commission) values (60, 'Butch', 'Russia', 11);
insert into salesman (salesman_id, name, city, commission) values (61, 'Arlen', 'Sweden', 14);
insert into salesman (salesman_id, name, city, commission) values (62, 'Quintin', 'China', 9);
insert into salesman (salesman_id, name, city, commission) values (63, 'Adorne', 'French Polynesia', 13);
insert into salesman (salesman_id, name, city, commission) values (64, 'Franni', 'Belarus', 12);
insert into salesman (salesman_id, name, city, commission) values (65, 'Laurence', 'Brazil', 10);
insert into salesman (salesman_id, name, city, commission) values (66, 'Lynn', 'Cuba', 10);
insert into salesman (salesman_id, name, city, commission) values (67, 'Kati', 'Macedonia', 12);
insert into salesman (salesman_id, name, city, commission) values (68, 'Sophie', 'Honduras', 11);
insert into salesman (salesman_id, name, city, commission) values (69, 'Joleen', 'Portugal', 11);
insert into salesman (salesman_id, name, city, commission) values (70, 'Natal', 'Poland', 9);
insert into salesman (salesman_id, name, city, commission) values (71, 'Shannah', 'Portugal', 14);
insert into salesman (salesman_id, name, city, commission) values (72, 'Laurent', 'Canada', 10);
insert into salesman (salesman_id, name, city, commission) values (73, 'Dirk', 'Bulgaria', 11);
insert into salesman (salesman_id, name, city, commission) values (74, 'Sayers', 'China', 13);
insert into salesman (salesman_id, name, city, commission) values (75, 'Madelene', 'Pakistan', 10);
insert into salesman (salesman_id, name, city, commission) values (76, 'Claudette', 'Paraguay', 10);
insert into salesman (salesman_id, name, city, commission) values (77, 'Caresse', 'United States', 14);
insert into salesman (salesman_id, name, city, commission) values (78, 'Angelina', 'Colombia', 13);
insert into salesman (salesman_id, name, city, commission) values (79, 'Shoshana', 'Serbia', 11);
insert into salesman (salesman_id, name, city, commission) values (80, 'Jessy', 'China', 14);
insert into salesman (salesman_id, name, city, commission) values (81, 'Osmond', 'Belarus', 10);
insert into salesman (salesman_id, name, city, commission) values (82, 'Jan', 'Chile', 12);
insert into salesman (salesman_id, name, city, commission) values (83, 'Jackson', 'United States', 11);
insert into salesman (salesman_id, name, city, commission) values (84, 'Nils', 'China', 10);
insert into salesman (salesman_id, name, city, commission) values (85, 'Martino', 'China', 10);
insert into salesman (salesman_id, name, city, commission) values (86, 'Cheri', 'Indonesia', 10);
insert into salesman (salesman_id, name, city, commission) values (87, 'Rocky', 'Colombia', 10);
insert into salesman (salesman_id, name, city, commission) values (88, 'Burnaby', 'United States', 10);
insert into salesman (salesman_id, name, city, commission) values (89, 'Shanan', 'Chile', 9);
insert into salesman (salesman_id, name, city, commission) values (90, 'Laura', 'China', 14);
insert into salesman (salesman_id, name, city, commission) values (91, 'Greta', 'Greece', 9);
insert into salesman (salesman_id, name, city, commission) values (92, 'Tyrone', 'Russia', 11);
insert into salesman (salesman_id, name, city, commission) values (93, 'Dory', 'Philippines', 9);
insert into salesman (salesman_id, name, city, commission) values (94, 'Marget', 'United States', 13);
insert into salesman (salesman_id, name, city, commission) values (95, 'Rollie', 'Russia', 11);
insert into salesman (salesman_id, name, city, commission) values (96, 'Mohammed', 'Czech Republic', 9);
insert into salesman (salesman_id, name, city, commission) values (97, 'Lona', 'Philippines', 11);
insert into salesman (salesman_id, name, city, commission) values (98, 'Arabelle', 'Indonesia', 10);
insert into salesman (salesman_id, name, city, commission) values (99, 'Matthew', 'Estonia', 11);
insert into salesman (salesman_id, name, city, commission) values (100, 'Bale', 'Czech Republic', 10);
